# Site settings
title: Entreprendre SagLac
email: info@saglac.io
description: Discussions entre entrepreneurs du Saguenay-Lac-St-Jean. Entraidons nous pour grandir ensemble!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://entreprendre.saglac.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
